CREATE TABLE IF NOT EXISTS clientes (
    id              INT UNSIGNED      NOT NULL AUTO_INCREMENT,
    numero_interno  SMALLINT UNSIGNED NOT NULL,
    nombre          VARCHAR(80)       NOT NULL,
    apellido        VARCHAR(80)       NOT NULL,
    dni             VARCHAR(15)       DEFAULT NULL,
    direccion       VARCHAR(150)      DEFAULT NULL,
    barrio          VARCHAR(80)       DEFAULT NULL,
    telefono        VARCHAR(20)       DEFAULT NULL,
    whatsapp        VARCHAR(20)       DEFAULT NULL,
    email           VARCHAR(120)      DEFAULT NULL,
    plan_id         SMALLINT UNSIGNED DEFAULT NULL,
    precio_mensual  DECIMAL(10,2)     NOT NULL,
    fecha_alta      DATE              NOT NULL,
    estado          ENUM('activo','suspendido','baja') NOT NULL DEFAULT 'activo',
    observaciones   TEXT              DEFAULT NULL,
    created_at      TIMESTAMP         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP         NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP         NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_clientes_numero (numero_interno),
    KEY idx_clientes_estado   (estado),
    KEY idx_clientes_apellido (apellido),
    KEY idx_clientes_dni      (dni),
    KEY idx_clientes_deleted  (deleted_at),
    CONSTRAINT fk_clientes_plan FOREIGN KEY (plan_id) REFERENCES planes (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
