CREATE TABLE IF NOT EXISTS empresa (
    id         TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    nombre     VARCHAR(100)     NOT NULL,
    logo_path  VARCHAR(255)     DEFAULT NULL,
    telefono   VARCHAR(20)      DEFAULT NULL,
    email      VARCHAR(120)     DEFAULT NULL,
    direccion  VARCHAR(200)     DEFAULT NULL,
    updated_at TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
